# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e739e163f7a7ed8b267e69f4d7a16393432e8ed7dbf4cfe9e38006e96f11e214993b30c2eeeafc645a76786cccecbc426bb806be9a6836a8820c7e9f418c1dce

test:
  secret_key_base: b5436dfe3cec8d831962532e1ac2b1a95238cdbcdd3bd68b2534e53911f50b800b100c0214a6fcd717a87e14e3821e50521e4ff9f1713f28970aea4927fd781c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
